# Paste your secret API keys here.

GEMINI_API_KEY = "AIzaSyDe9AM1ZmEFA7VTnYFqA8zrDJCX2vWUyf0"
GOOGLE_MAPS_API_KEY = "AIzaSyB6oZo6EPoKnmmd1qZBEqQMPqVHq-zq9c0"
OPENCHARGEMAP_API_KEY = "f97ec656-40bd-4d4c-8301-c451d5d3ec3a"
